title = "Novo dia"
theme = "chicago7"
themesDir = "themes"
enableRobotsTXT = true
hasCJKLanguage = true
baseURL = ""

[pagination]
pagerSize = 10

[markup.goldmark.renderer]
hardWraps = true

# these values are hugo built in markup config
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = false
noClasses = false
noHl = false
style = 'bw'
tabWidth = 4

[params]
description = "Tentando ser autor"
mainSections = ['posts']

[permalinks]
posts = "/posts/:year:month:day"

[menu]
[[menu.header]]
name = "Sobre"
url = "sobre"
weight = 40

[[menu.header]]
name = "Posts"
url = "posts"
weight = 20

[[menu.header]]
name = "Projetos"
url = "projetos"
weight = 30

